# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=6000),
        ),
    ]
