# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160917_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubReddit',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subreddit',
            new_name='topic',
        ),
    ]
